app/users/forms.py
from flask.ext.wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField, ValidationError
from wtforms import TextAreaField, FileField, HiddenField
from wtforms.validators import Required, EqualTo, Email, Length, Optional
from app.users.utils import check_password


class LoginForm(Form):
    email = TextField('Email address', [Required(), Email()])
    password = PasswordField('Password', [Required()])


class RegisterForm(Form):
    name = TextField('Full Name', [Required()])
    email = TextField('Email address', [Required(), Email()])
    password = PasswordField('Password', [Required()])
    confirm = PasswordField('Repeat Password', [
        Required(),
        EqualTo('password', message='Passwords must match')
    ])
    accept_tos = BooleanField('', [Required()])

    # recaptcha = RecaptchaField()

    @staticmethod
    def validate_password(form, field):
        """docstring for validate_password"""
        strength = check_password(field.data)
        if strength not in ['Medium', 'Strong', 'Very Strong']:
            raise ValidationError(
                'Your password is %s, it should be > 6 '
                'chars and contain at least one digit' % strength)


class ForgotForm(Form):
    email = TextField(
        'Please enter your e-mail address', [Required(), Email()])
    # recaptcha = RecaptchaField()


class ProfileForm(Form):
    name = TextField('Full Name', [
        Required(),
        Length(min=4, max=50),
    ])

    mobile = TextField(
        'Mobile',
        description="example: +1 899 3036120")

    website = TextField(
        'Your homepage',
        [
            Optional(),
            Length(min=4, max=250)
        ],
        description="example: http://www.example.com"
    )

    description = TextAreaField()

    photo = FileField(
        'Your photo',
        description='Upload your photo, best size is 245X245 pixels and of type PNG'
    )

app/users/views.py
import os
import md5
import hashlib
import base64
from flask import Blueprint, request, render_template
from flask import flash, g, session, redirect, url_for
from flask import make_response
from flask import current_app
from flask_mail import Message
from werkzeug import secure_filename
from app import db
from app import mail
from app.mail_utility import send_email
from app.users.forms import RegisterForm, LoginForm, ProfileForm, ForgotForm
from app.users.constants import UPLOAD_FOLDER
from app.users.models import User, Role, users_roles
from app.users.utils import allowed_image_file
from app.users.decorators import login_required, templated
from itsdangerous import URLSafeTimedSerializer
from flask.ext.babel import gettext
from flask.ext.security.utils import encrypt_password, verify_password
from flask.ext.principal import identity_changed, Identity, AnonymousIdentity

from app import guest_per, user_per, blogger_per, admin_per

mod = Blueprint('users', __name__, url_prefix='/users')


def authorize(user):
    session['user_id'] = user.id


def is_logged():
    return g.user


@mod.before_app_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])


@mod.route('/dashboard')
@mod.route('/home')
@user_per.require(http_exception=403)
def home():
    return render_template(
        "users/me.html", user=g.user
    )


@mod.route('/pleaseconfirm')
def pleaseconfirm():
    if g.user:
        send_confirmation()
    return render_template("users/pleaseconfirm.html", user=g.user)


@mod.route("/confirm/<string:token>", methods=['GET', 'POST'])
def confirm(token):
    """docstring for confirm"""
    try:
        email = confirm_token(token)
    except:
        flash(gettext(u'The confirmation link is invalid or has expired.'), 'danger')

    user = User.query.filter_by(email=email).first_or_404()

    if user.is_confirmed():
        flash(gettext(u'Account already confirmed. Please login.'), 'success')
    else:
        user.confirmed = True
        user.active = True
        db.session.commit()
        flash(gettext(u'You have confirmed your account. Thanks!'), 'success')

    return redirect(url_for('users.home'))


def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    return serializer.dumps(email, salt=current_app.config['SECURITY_PASSWORD_SALT'])


def confirm_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    try:
        email = serializer.loads(
            token,
            salt=current_app.config['SECURITY_PASSWORD_SALT'],
            max_age=expiration
        )
    except:
        return False
    return email


@mod.route("/reconfirm/<string:alias>", methods=['GET', 'POST'])
def reconfirm(alias):
    """docstring for reconfirm"""
    if g.user:
        send_confirmation()
    return redirect(url_for('users.home'))


def send_confirmation():
    """docstring for send_confirmation"""

    token = generate_confirmation_token(str(g.user.get_email()))
    lnk = url_for('users.confirm', token=token, _external=True)
    conflnk_html = '<a href="%s">%s</a>' % (lnk, lnk)

    msg = Message(
        gettext(u"Please confirm your account at vision website"),
        sender=current_app.config['NOREPLY_EMAIL'],
        recipients=[g.user.get_email()]
    )
    msg.body = "\nWelcome\n\n"
    msg.body += "\nPlease confirm your account by clicking this link:\n"
    msg.body += "\n%s" % lnk
    msg.body += "\nFuture notifications will be sent to this email address."
    msg.body += "\nThank you,"
    msg.body += "\n\nTeam."

    msg.html = "Hi, Welcome"
    msg.html += "<br><br>Please confirm your account by clicking this link:"
    msg.html += "\n%s" % conflnk_html
    msg.html += "<br>Future notifications will be sent to this email address."
    msg.html += "<br>Thank you,"
    msg.html += "<br><br>Team."
 
 
    if current_app.config['SEND_EMAILS'] == True:
        mail.send(msg)


# @mod.route('/forgot-password', methods=['GET', 'POST'])
# def forgot():
#     if 'user_id' in session:
#         return redirect(url_for('users.home'))
#
#     form = ForgotForm(request.form)
#     if request.method == 'POST':
#         if form.validate_on_submit():
#             user = User.query.filter_by(email=form.email.data).first()
#             if user:
#                 return user
#
#     # make sure data are valid, but doesn't validate password is right
#     return render_template("users/forgot.html", form=form)



@mod.route('/login', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    if 'user_id' in session:
        return redirect(url_for('users.home'))

    form = LoginForm(request.form)

    # make sure data are valid, but doesn't validate password is right
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            # we use werzeug to validate user's password
            if user and verify_password(form.password.data, user.password):
                # the session can't be modified as it's signed,
                # it's a safe place to store the user id
                authorize(user)
                # Tell Flask-Principal the identity changed
                identity_changed.send(current_app._get_current_object(),
                                      identity=Identity(user.id))

                flash(gettext(u'Welcome') + " " + user.name)
                if not user.is_confirmed():
                    return redirect(url_for('users.pleaseconfirm', next=url_for('home.home')))
                return redirect(url_for('home.home'))
        flash(gettext(u'Wrong email or password'), 'error-message')

    return render_template('users/login.html', form=form)


@mod.route('/logout', methods=['GET'])
def logout():
    """ Logout action.  """
    if 'user_id' in session:
        del session['user_id']
        g.user = None

        # Tell Flask-Principal the user is anonymous
    identity_changed.send(current_app._get_current_object(),
                          identity=AnonymousIdentity())

    response = make_response(redirect(url_for('users.login')))
    response.set_cookie('sc', '', expires=0)
    return response


@mod.route('/register', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # create an user instance not yet stored in the database
        # check if email exists
        try:
            exists = db.session.query(User).filter(
                User.email == form.email.data).first()

            if exists:
                flash(
                    gettext(
                        u'User with this e-mail was registered already.'
                        u' If you forgot your password click ' +
                        u'<a href="%s">remind password</a>' % url_for(
                            'users.forgot')
                    ))
                # redirect user to the 'home' method of the user module.
                return redirect(url_for('users.register'))
        except Exception as e:
            current_app.logger.exception(e)

        alias = ''.join(e for e in form.name.data if e.isalnum())
        try:
            alias_exists = db.session.query(User).filter(
                User.alias == alias).one()
        except Exception as e:
            current_app.logger.exception(e)
            alias_exists = None

        if alias_exists:
            alias = hashlib.md5(form.email.data).hexdigest()

        user = User(
            name=form.name.data,
            email=form.email.data,
            alias=alias,
            password=encrypt_password(form.password.data)
        )

        # add default
        userRole = db.session.query(Role).filter(Role.name == "user").first()
        if userRole is not None:
            # createUserRole =  users_roles( user_id = user.id
            #     , role_id = userRole.id );
            # adminRole =  db.session.query(Role).filter(Role.name == "admin").first()
            # user.roles.append(adminRole)
            user.roles.append(userRole)

        # Insert the record in our database and commit it
        db.session.add(user)
        db.session.flush()

        # Log the user in, as he now has an id
        authorize(user)

        try:
            os.mkdir(os.path.join(UPLOAD_FOLDER, str(user.id)), 0775)
        except OSError as e:
            current_app.logger.exception(e)

        db.session.commit()
        email_recipients = [item.email for item in db.session.query(User).all()
                            if item.has_role(Role.query.get(1))
                            ]
        msg = 'A new user with login {} was created'.format(user.name)

        if current_app.config['SEND_EMAILS'] == True:
            try:
                send_email(email_recipients, msg)
            except Exception as e:
                pass

        # flash will display a message to the user
        flash(gettext(u'Thanks for registering'))
        # redirect user to the 'home' method of the user module.
        if not user.is_confirmed():
            return redirect(url_for('users.pleaseconfirm', next=url_for('users.home')))

    return render_template('users/register.html', form=form)


@mod.route("/profile", methods=['GET', 'POST'])
@user_per.require(http_exception=403)
@templated('users/profile.html')
def profile():
    user = g.user
    form = ProfileForm(request.form, obj=user)

    if form.validate_on_submit():
        user.name = form.name.data
        user.mobile = form.mobile.data
        user.website = form.website.data
        user.description = form.description.data

        if 'photo' in request.files:
            # remove user photo and thumbs

app/templates/users/_formhelpers.html
{% macro render_field(field) %}
	<dt>{{ field.label }}
	<dd>{{ field(**kwargs)|safe }}
	{% if field.errors %}
		<ul class=errors>
		{% for error in field.errors %}
			<li>{{ error }}</li>
		{% endfor %}
		</ul>
	{% endif %}
	</dd>
{% endmacro %}

app/templates/users/forgot.html
{% extends "base.html" %}
{% block top %}
{% endblock %}
{% block rightcontent %}
{% endblock %}
{% block header %}
<header></header>
{% endblock %}

{% block content %}
<div class="login-form-container">
	<div class="title-container title container-background">
		<div>PASSWORD REMINDER</div>
	</div>
	<div class="arial container-background">
		{% from "forms/macros.html" import render_field %}
		<form class="form fs13" method="POST" action="{{ url_for('users.forgot') }}">
			{{ form.csrf_token }}
			{{ render_field(form.email, class="input text") }}
			<div>
				<br>
				To ensure the security of your information, we ask that you type the code (displayed below) in the text box.
			</div>
			<label>Are you a human?</label>
			{{ form.recaptcha }}
			<input type="submit" value="Submit" class="btn">
		</form>
	</div>
</div>
{% endblock %}
{% block bottommenu %}
{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}
{% block top %}
{% endblock %}
{% block rightcontent %}
{% endblock %}
{% block header %}
<header></header>
{% endblock %}

{% block content %}
<div class="login-form-container">
  <div class="title-container title form-container container-shadow container-background">
    <div class="join-us">Login</div>
  </div>
  <div class="form-container arial container-background">
    {% from "forms/macros.html" import render_field %}
    <form class="form fs13" method="POST" action="{{ url_for('users.login') }}" id="visionLoginForm">
      {{ form.csrf_token }}
      {{ render_field(form.email, class="input text") }}
      {{ render_field(form.password, class="input text") }}
      <a href="{{ url_for('users.register') }}" rel=nofollow>Register</a> | <a href="{{ url_for_security('forgot_password') }}" rel="nofollow">Forgot password ?</a>
      <input type="submit" value="Login" class="btn">
    </form>
  </div>
</div>
<script>
    var loginForm = document.getElementById("visionLoginForm");
    loginForm.onsubmit = function(e) {loginAndGetToken(e)};
    function loginAndGetToken(e) {
        e.preventDefault();
        var username = document.getElementById("email").value;
        var password = document.getElementById("password").value;
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4) {
                if (this.status == 200) {
                    var response = JSON.parse(this.responseText);
                    localStorage.setItem("apiToken", response.token);
                    localStorage.setItem("Id", response.user_id);
                }
                loginForm.submit();
            }
        };
        xhttp.open("GET", '/api/v1.0/token', true);
        xhttp.setRequestHeader("Authorization", "Basic " + btoa(username + ":" + password));
        xhttp.send();
    }
</script>
{% endblock %}
{% block bottommenu %}
{% endblock %}
{% block js_footer %}
{% endblock %}

app/templates/users/me.html
{% extends "dashboard.html" %}

<div class="title-container title container">
	{% block navbar_right %}
	<li><a href="" title="" class="" id="">test</a></li>
	<li><div class="pull-left"><img src="{{user.avatar(28)}}">{{ user.name|striptags|title }}</div></li>
	{% endblock %}

	{% block profile_image %}
	<div class="pull-left"><img src="{{user.avatar(28)}}"> {{ user.name }}'s dashboard</div>
	{% endblock %}

	{% block dashboard_menu %}
	{% include 'widgets/dashboard-menu.html' %}
	{% endblock %}
</div>
{% block content %}
{% endblock %}
{% block panel_footer %}
{% endblock %}
{% block bottommenu %}
{% endblock %}

app/templates/users/pleaseconfirm.html
{% extends "dashboard.html" %}

{% block content_footer %}
{% endblock %}

{% block page %}
<div class="container" style="height: 300px;margin-top:200px">
	<div class="alert alert-danger">
		Your email is not confirmed yet.
		We have sent you a confirmation letter recently. Please follow instructions described in the letter
		in order to confirm your e-mail.
		If you still did not receive any email from us
		<a href="{{ url_for('users.reconfirm', alias=user.alias) }}">click here</a>
	</div>
</div>
{% endblock %}

app/templates/users/profile.html
{% extends "dashboard.html" %}

<div class="title-container title container">
  {% block dashboard_menu %}
  {% include 'widgets/dashboard-menu.html' %}
  {% endblock %}
</div>

{% block panel_body %}
  {% if session.help %}
  <div class="jumbotron">
    <h1>
      {{ session.help.greeting }}
    </h1>
    <p>
    {{ session.help.suggestion }}
    </p>
  </div>
  {% endif %}
{% endblock %}

{% block content %}
<h2>Edit profile</h2>
{% from "forms/macros.html" import form_field %}
<div class="profile-form-container">
  <div class="photo pull-left ">
    {% if user.photo == '' or not user.photo %}
      <img src="{{ url_for('static', filename='img/no-photo.png') }}" alt="no photo">
    {% endif %}
    {% if user.photo %}
      {% if user.photo.startswith(('http','https')) %}
      <img src="{{ user.photo }}" alt="{{ user.alias}}" />
      {% else %}
    {% endif %}
    <img src="/photo/thumb/245/{{ user.alias }}/{{ user.photo }}" alt="{{ user.alias }}">
    {% endif %}
  </div>
  <div class="pull-right">
    <form method="POST" action="" enctype="multipart/form-data" class="form-horizontal" role="form">
      {{ form.csrf_token }}
      Change your photo {{ form_field(form.photo, class="form-control input-lg") }}
      {{ form_field(form.name, class="form-control input-lg") }}
      {{ form_field(form.description, class="form-control input-lg", rows=4) }}
      {{ form_field(form.website, class="form-control input-lg", rows=4) }}
      {{ form_field(form.mobile, class="form-control input-lg") }}
      <input type="submit" value="Save" class="btn btn-block btn-lg btn-primary">
    </form>
  </div>
</div>
{% endblock %}

{% block content_footer %}
{% endblock %}

{% block bottommenu %}
{% endblock %}

app/templates/users/register.html
{% extends "base.html" %}
{% block header %}
<header></header>
{% endblock %}
{% block top %}
{% endblock %}
{% block rightcontent %}
{% endblock %}
{% block content %}
<div class="register-form-container">
	<div class="title-container title form-container container-background">
		<div class="join-us">Register</div>
	</div>
	<div class="form-container arial container-background">
		{% from "forms/macros.html" import render_field %}
		<form class="form fs13" method="POST" action="{{ url_for('users.register') }}">
			{{ form.csrf_token }}
			{{ render_field(form.name, class="input text") }}
			{{ render_field(form.email, class="input text") }}
			{{ render_field(form.password, class="input text") }}
			{{ render_field(form.confirm, class="input text") }}
			<p>
			<div style="float:left">
				I accept <a href="#" title="Terms of use" target="_blank">Terms of use</a>
			</div>
			<div class="float:left">
				{{ form.accept_tos|safe }}
				{% if form.accept_tos.errors %}
				<ul class="errors">{% for error in form.accept_tos.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
				{% endif %}
			</div>
			</p>
			{#
			<label>Human ?</label>
			{{ form.recaptcha }}
			#}
			<input type="submit" value="Register" class="btn">
		</form>
	</div>
</div>
{% endblock %}
{% block bottommenu %}
{% endblock %}