app/home/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import session
from flask import Blueprint
from flask import render_template
from flask import g, request
from flask import current_app

from app import babel
from app.users.models import User
from app.home.models import _is_blogger, _get_news, _get_blog_meta
import sqlalchemy_utils
from flask_login import current_user
import markdown
from flask import Markup
from app.pages.storage import get_page_by_title, get_page_by_slug, process_page, isblogger
from app.pages.views import render
from flask import jsonify, redirect, url_for, abort

mod = Blueprint('home', __name__, url_prefix='')


@mod.before_app_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None

    if 'user_id' in session:
        if session['user_id'] is not None:
            g.user = User.query.get(session['user_id'])
            if not g.user:
                del session['user_id']

    g.locale = get_locale()
    sqlalchemy_utils.i18n.get_locale = get_locale


@babel.localeselector
def get_locale():
    if 'locale' in session:
        if session['locale'] is not None:
            g.locale = session['locale']
            return g.locale

    return request.accept_languages.best_match(
        current_app.config['LANGUAGES'].keys()
    )


@babel.timezoneselector
def get_timezone():
    user = getattr(g, 'user', None)
    if user is not None:
        return user.timezone

    # Use the browser's language preferences to select an available translation
    # @babel.localeselector
    # def get_locale():
    # translations = [str(translation) for translation in babel.list_translations()]
    # return request.accept_languages.best_match(translations)

@mod.route('/api/v1/manufacturers', methods=['GET'] )
def manufacturers():
    return jsonify(first='1900', second='1901')

@mod.route('/lang/<string:lang>', methods=['GET'])
# @guest_per.require(http_exception = 403)
def lang(lang):
    """docstring for lang"""
    if lang not in current_app.config['LANGUAGES']:
        lang = current_app.config['BABEL_DEFAULT_LOCALE']

    session['locale'] = lang
    g.locale = lang

    posts = _get_news(current_user)
    meta = _get_blog_meta()

    page = get_page_by_slug(u'vision-diagnostic')

    canEdit = None
    if page is not None:
        canEdit = isblogger(current_user=g.user)
        process_page(page, render=render)

    return render_template(
        'home/index.html'
        , user=g.user
        , posts=posts
        , meta=meta
        , isblogger=canEdit
        , page=page
    )


@mod.route('/', methods=['GET'])
# @guest_per.require(http_exception = 403)
def home():
    """docstring for home."""
    # posts = _get_news(current_user)
    posts = []
    meta = _get_blog_meta()

    page = get_page_by_slug(u'vision-diagnostic')

    canEdit = None
    if page is not None:
        canEdit = isblogger(current_user=g.user)
        process_page(page, render=render)

    return render_template(
        'home/index.html'
        , user=g.user
        , posts=posts
        , meta=meta
        , isblogger=canEdit
        , page=page
    )


@mod.route('/wiki/developers', methods=['GET'])
# @guest_per.require(http_exception = 403)
def wiki_devs():
    """temporary expose README.md from git as a wiki file for developers"""
    with open('README.md', 'r') as fh:
        content = fh.read()
        content = Markup(markdown.markdown(content))

    return render_template(
        'wiki/developers.html',
        **locals()
    )


from .models import get_images


@mod.route('/images', methods=['POST'])
def images():
    if request.is_xhr:
        images = get_images()
        return jsonify({'images': images})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


from app.pages.storage import isblogger, process_page, get_page_by_tag_slug, get_pages_by_tag
from app.pages.views import render


@mod.route('/<string:tag>/<string:slug>', methods=['GET'])
def show_page_tag(tag, slug):
    page = get_page_by_tag_slug(tag, slug)
    if page is None:
        abort(404)

    canedit = isblogger(current_user=g.user)
    process_page(page, render=render)

    return render_template(
        "pages/page.html"
        , page=page
        , isblogger=canedit
    )


from app import app
from app.admin.storage import ul_menu_creation


@app.context_processor
def custom_function():
    def ul_menu(tag):
        return ul_menu_creation(tag)

    def li_menu(tag):
        return ul_menu_creation(tag, use_ul=False)

    return dict(ul_menu=ul_menu, li_menu=li_menu)

app/pages/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, request, render_template
from flask import flash, g, session, redirect, url_for ,flash
from app import blogger_per
from .storage import *
from .forms import PageEditor
from flask.ext.principal import PermissionDenied
from flask.ext.babel import gettext
from app.users.models import User

mod = Blueprint('pages', __name__, url_prefix='/pages')
#true for the moment
render = True

@mod.before_app_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    set_locale()
    g.user = None

    if 'user_id' in session:
        if session['user_id'] is not None:
            g.user = User.query.get(session['user_id'])

@mod.route("/<int:page_id>/", defaults={"page_id": None} )
@mod.route("/<int:page_id>/")
def page(page_id):
    global render
    page = get_page_by_id(page_id)
    canedit = isblogger(current_user = g.user)

    process_page(page, render = render)

    return render_template(
         "pages/page.html"
        ,page = page
        ,isblogger = canedit
    )

@mod.route("/delete/<int:page_id>/")
def delete(page_id):
    page = get_page_by_id(page_id)
    if page is not None:
        pid = delete_page_by_id(page.id)
        if pid is not None:
            flash(gettext(u"Page successfully delete"), gettext(u"info"))
        else:
            flash(gettext(u"Could not delete page"), gettext(u"warning"))

    else:
        flash(gettext(u"Page dosen't exists"), gettext(u"warning"))

    return redirect(url_for("pages.show"))


@mod.route("/show/", methods=['GET', 'POST'])
@mod.route("/", methods=['GET', 'POST'])
def show():
    global render
    pages  = get_all_pages()
    canedit = isblogger(current_user = g.user)

    for page in pages:
        process_page(page, render = render)

    return render_template(
         "pages/show.html"
        ,pages = pages
        ,isblogger = canedit
    )

@mod.route("/editor/<int:page_id>/", methods=['GET', 'POST'] )
@mod.route("/editor/", defaults={"page_id": None} ,methods=['GET', 'POST'] )
def editor(page_id):
    try:
        with blogger_per.require():
            if request.method == 'POST':
                form = PageEditor(request.form)
                if form.validate():
                    if form.tag.data.lower() not in ('forum','lang','users','pages','admin'):
                        page = get_page_by_id(page_id)
                        if (page is not None) and page.id == page_id:
                            pass
                        else:
                            page = Pages()

                        pid = store_form_data(form,current_user, page)
                        flash(gettext(u"Page successfully added!"), gettext(u"info"))
                        return redirect(url_for(
                                 "pages.page"
                                ,page_id = pid
                        ))
                    else:
                        flash(gettext(u"Tag {0} is forbidden".format(form.tag.data)), gettext(u"warning"))
                        return render_template(
                            "pages/editor.html"
                            ,form = form
                            ,page_id = page_id
                        )
                else:
                    flash(gettext(u"There were errors in page submission"), gettext(u"warning"))
                    return render_template(
                        "pages/editor.html"
                        ,form = form
                        ,page_id = page_id
                    )
            else:
                if page_id is not None:
                    page = get_page_by_id(page_id)
                    if (page is not None) \
                            and (is_author(page.author_id)):
                        form = PageEditor(
                             title = page.title
                            ,slug = page.slug
                            ,text = page.text
                            ,tag = page.tag
                        )
                        return render_template(
                             "pages/editor.html"
                            ,form = form
                            ,page_id = page_id
                        )
                    else:
                        flash(gettext(u"You do not have the rights to edit this page"),gettext(u"warning"))
                        return redirect(url_for("pages.show"))

            form = PageEditor()
            return render_template(
                 "pages/editor.html"
                ,form = form
                ,page_id = page_id
            )
    except PermissionDenied:
        flash(gettext(u"You do not have permissions to create or edit pages"), gettext(u"warning"))
        return redirect(url_for("pages.show"))

app/templates/pages/editor.html
{% extends "base.html" %}

{% block title %}
    Vision Diagnostic - edit page
{% endblock title %}

{% block extrastyle %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown/2.8.0/css/bootstrap-markdown.min.css" rel="stylesheet"/>
{% endblock extrastyle %}

{% block topcontent %}
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body row" id="image_data" style="padding-bottom: 1%;padding-top: 1%;">

                </div>
                <div class="col-md-12 modal-body" id="btn" style="float:left">
                     <button type="button" class="btn btn-primary" id="toMarkUp">
                         Add to MarkDown
                     </button>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div>

        </div>
    </div>
    <form class="form-horizontal" action="{{ url_for('pages.editor', page_id=page_id or None) }}" method="POST">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend> {{ _('Page Editor') }}</legend>
            <div class="form-group">
                <div class="input-group col-md-12">
                    {% for error in form.title.errors %}
                        <div style="color: red;">[{{ error }}]</div>
                    {% endfor %}
                </div>
                <label class="control-label" for="title">
                    {{ _("Title") }}
                </label>
                <div class="input-group col-md-12">
                    {{ form.title(placeholder=_('Title'), id = "title", class = "form-control", required = "" ) }}
                </div>
            </div>
            <div class="form-group">
                <div class="input-group col-md-12">
                    {% for error in form.slug.errors %}
                        <div style="color: red;">[{{ error }}]</div>
                    {% endfor %}
                </div>
                <label class="control-label" for="slug">
                    <div class="input-group col-md-12">
                        {{ _("Slug") }}
                    </div>
                </label>
                <div class="input-group col-md-12">
                    {{ form.slug(placeholder=_('Slug'), id = "slug", class = "form-control", required = "" ) }}
                </div>
                <div class="input-group col-md-12">
                    <strong> alphanumeric characters and - are allowed </strong>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group col-md-12">
                    {% for error in form.tag.errors %}
                        <div style="color: red;">[{{ error }}]</div>
                    {% endfor %}
                </div>
                <label class="control-label" for="tag">
                    {{ _("Category") }}
                </label>
                <div class="input-group col-md-12">
                    {{ form.tag(placeholder=_('Tag'), id = "tag", class = "form-control", required = "" ) }}
                    <p>
                        <div class="input-group col-md-12">
                            <strong> alphanumeric characters and - are allowed </strong>
                        </div>
                        <strong> * Forbidden tags: forum,lang,users,pages,admin,</strong> </p>
                </div>
            </div>
            <div class="form-group">
                 <div class="input-group col-md-12">
                    {% for error in form.text.errors %}
                        <div style="color: red;">[{{ error }}]</div>
                    {% endfor %}
                </div>
                <div class="input-group col-md-12" style="padding-bottom: 5px;">
                     <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg" id="media">
                         Add Media
                     </button>
                </div>
                <div class="input-group col-md-12">
                    {{ form.text(placeholder=_('Page text'), required = "", data_provide = "markdown", rows = "16") }}
                    <span class="help-block">
                        {{ _('Learn more about') }} <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">MarkDown</a>
                    </span>
                </div>

            </div>
            <div class="form-group">
                <div class="input-group col-md-12">
                    {{ form.submit(id="submit", class="btn btn-primary") }}
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown/2.8.0/js/bootstrap-markdown.min.js"> </script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/markdown.js/0.5.0/markdown.min.js"> </script>

    <script type="text/javascript">
        // Generates a URL-friendly "slug" from a provided string.
        // For example: "This Is Great!!!" transforms into "this-is-great"
        function generateSlug (value) {
          // 1) convert to lowercase
          // 2) remove dashes and pluses
          // 3) replace spaces with dashes
          // 4) remove everything but alphanumeric characters and dashes
          return value.toLowerCase().replace(/-+/g, '').replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
        };

        $(document).ready()
        {
            $(".form-group #text").markdown({
                 autofocus:true
                ,savable:false
            });

            $(".form-horizontal #title").keyup(function(event){
                var value = $(this).val();
                $(".form-horizontal #slug").val(generateSlug(value));
            });

            var img_path = "{{ url_for('static' , filename='img/uploads/' ) }}";

            $(".form-group #media").click(function (e) {

                $(".modal .modal-content #btn").addClass('hidden');

                $.post('{{ url_for("home.images") }}'
                    , function (data) {
                        if (data.images) {
                            $(".modal .modal-content #image_data").html("");
                            /* loop through all images and display them */
                            data.images.forEach(function (item) {
                                var data = "<div class='col-md-4 no-border img-size' style=''>";
                                var thumb = img_path + item.path;
                                data += "<img src='" + thumb + "' alt='" + item.name + "' id='img-" + item.id + "' width='120px' height='120px' class='img-unsel' />";
                                data += "</div>";
                                $(".modal .modal-content #image_data").append(data);

                            });
                            $(".modal .modal-content #btn").removeClass('hidden');
                        }
                    }).fail(function () {
                        $(".modal .modal-content #image_data").html("");
                        $(".modal .modal-content #image_data").append("An Error has occurred!");
                    });
            });

            $('.modal .modal-content #image_data').on('click', 'img', function () {
                if ($(this).hasClass('img-unsel')) {
                    $(this).removeClass('img-unsel').addClass('img-sel');
                } else {
                    if ($(this).hasClass('img-sel')) {
                        $(this).removeClass('img-sel').addClass('img-unsel');
                    }
                }
            });

            $(".modal .modal-content #toMarkUp").click(function () {
                $(".modal .modal-content #image_data .img-sel").each(function (index) {
                    console.log($(this).prop('src') + " " + $(this).prop('alt'));
                    var data = '\n![' + $(this).prop('alt') + '](' + $(this).prop('src') + ' "' + $(this).prop('alt') + '")';
                    $('.form-group #text').append(data);
                });
                $('.modal').modal('hide');
            });
        }
    </script>
{% endblock js %}2

app/templates/pages/page.html
{% extends "base.html" %}

{% block title %}
    Vision Diagnostic - {{ page.title }}
{% endblock title %}

{% block topcontent %}
    <div class="modal fade" id="confirmModal" >
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title"> {{ _('Are you sure you want to delete this post ?') }}</h4>
                </div>
                <div class="modal-footer">
                    <form action="{{ url_for('pages.delete', page_id=page.id) }}" method="POST">
                        <button type="button" class="btn btn-default" data-dismiss="modal"> {{ _('Cancel') }} </button>
                        <input type="submit" value="Yes" class="btn btn-primary" id="confirmedDelete"/>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <div class="row">
        <div class="col-md-12">
            <div class="box-header clearfix">
                {% if isblogger %}
                    <span class="pull-right">
                        {% if page.editable %}
                           <a href="{{ url_for('pages.delete', page_id=page.id) }}" id="delete">
                                <span class="glyphicon glyphicon-trash"></span>&nbsp; {{ _('Delete') }}
                            </a>&nbsp&nbsp&nbsp&nbsp
                            <a href="{{ url_for('pages.editor', page_id=page.id) }}" id="edit">
                                <span class="glyphicon glyphicon-edit"></span>&nbsp; {{ _('Edit') }}
                            </a>&nbsp&nbsp&nbsp&nbsp
                        {% endif %}
                            <a href="{{ url_for('pages.editor') }}" id="new">
                                <span class="glyphicon glyphicon-plus"></span>&nbsp; {{ _('New') }}
                            </a>
                    </span>
                {% endif %}
                <span class="pull-left">
                    <a href="{{ url_for('pages.page', page_id = page.id) }}">
                      <h1>{{ page.title }}</h1>
                    </a>
                </span>
            </div>
            <div class="box-body">
                <div class="">
                    {{ page.rendered_text | safe }}
                </div>
            </div>
        </div>
    </div>
{% endblock topcontent %}

{% block js %}
    <script>
        $(document).ready(function(){
            $("#delete").click(function(e){
                $('#confirmModal').modal('show');
                e.preventDefault()
            });
            $("img").addClass("center-block").addClass("img-responsive");
        });
    </script>
{% endblock js %}

app/templates/pages/show.html
{% extends "base.html" %}
{% block title %}
    Vision Diagnostic - show all pages
{% endblock title %}

{% block topcontent %}
    {% if isblogger %}
        <div class="row mb8 mt8">
            <div class="col-md-12">
                <span class="pull-right">
                    <a href="{{ url_for('pages.editor') }}" id="new">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; {{ _('New') }}
                    </a>
                </span>
            </div>
        </div>
    {% endif %}
    {% if pages %}
        {% for page in pages %}
            <div class="row">
                <div class="col-md-12">
                    <div class="box-header clearfix">
                        <div class="pull-left">
                            <a href="{{ page.url }}">
                                <h1>{{ _(page.title) }}</h1>
                            </a>
                        </div>
                        {% if isblogger %}
                            <div class="pull-right">
                            {% if page.editable %}
                                <a href="{{ url_for('pages.delete', page_id=page.id) }}" class="delete" >
                                    <span class="glyphicon glyphicon-trash">
                                    </span>&nbsp; {{ _('Delete') }}
                                </a>&nbsp&nbsp&nbsp&nbsp
                                <a href="{{ url_for('pages.editor', page_id=page.id) }}" id="edit">
                                    <span class="glyphicon glyphicon-edit"></span>&nbsp; {{ _('Edit') }}
                                </a>&nbsp&nbsp&nbsp&nbsp
                            {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}