app/home/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import session
from flask import Blueprint
from flask import render_template
from flask import g, request
from flask import current_app

from app import babel
from app.users.models import User
from app.home.models import _is_blogger, _get_news, _get_blog_meta
import sqlalchemy_utils
from flask_login import current_user
import markdown
from flask import Markup
from app.pages.storage import get_page_by_title, get_page_by_slug, process_page, isblogger
from app.pages.views import render
from flask import jsonify, redirect, url_for, abort

mod = Blueprint('home', __name__, url_prefix='')


@mod.before_app_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None

    if 'user_id' in session:
        if session['user_id'] is not None:
            g.user = User.query.get(session['user_id'])
            if not g.user:
                del session['user_id']

    g.locale = get_locale()
    sqlalchemy_utils.i18n.get_locale = get_locale


@babel.localeselector
def get_locale():
    if 'locale' in session:
        if session['locale'] is not None:
            g.locale = session['locale']
            return g.locale

    return request.accept_languages.best_match(
        current_app.config['LANGUAGES'].keys()
    )


@babel.timezoneselector
def get_timezone():
    user = getattr(g, 'user', None)
    if user is not None:
        return user.timezone

    # Use the browser's language preferences to select an available translation
    # @babel.localeselector
    # def get_locale():
    # translations = [str(translation) for translation in babel.list_translations()]
    # return request.accept_languages.best_match(translations)

@mod.route('/api/v1/manufacturers', methods=['GET'] )
def manufacturers():
    return jsonify(first='1900', second='1901')

@mod.route('/lang/<string:lang>', methods=['GET'])
# @guest_per.require(http_exception = 403)
def lang(lang):
    """docstring for lang"""
    if lang not in current_app.config['LANGUAGES']:
        lang = current_app.config['BABEL_DEFAULT_LOCALE']

    session['locale'] = lang
    g.locale = lang

    posts = _get_news(current_user)
    meta = _get_blog_meta()

    page = get_page_by_slug(u'vision-diagnostic')

    canEdit = None
    if page is not None:
        canEdit = isblogger(current_user=g.user)
        process_page(page, render=render)

    return render_template(
        'home/index.html'
        , user=g.user
        , posts=posts
        , meta=meta
        , isblogger=canEdit
        , page=page
    )


@mod.route('/', methods=['GET'])
# @guest_per.require(http_exception = 403)
def home():
    """docstring for home."""
    # posts = _get_news(current_user)
    posts = []
    meta = _get_blog_meta()

    page = get_page_by_slug(u'vision-diagnostic')

    canEdit = None
    if page is not None:
        canEdit = isblogger(current_user=g.user)
        process_page(page, render=render)

    return render_template(
        'home/index.html'
        , user=g.user
        , posts=posts
        , meta=meta
        , isblogger=canEdit
        , page=page
    )


@mod.route('/wiki/developers', methods=['GET'])
# @guest_per.require(http_exception = 403)
def wiki_devs():
    """temporary expose README.md from git as a wiki file for developers"""
    with open('README.md', 'r') as fh:
        content = fh.read()
        content = Markup(markdown.markdown(content))

    return render_template(
        'wiki/developers.html',
        **locals()
    )


from .models import get_images


@mod.route('/images', methods=['POST'])
def images():
    if request.is_xhr:
        images = get_images()
        return jsonify({'images': images})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


from app.pages.storage import isblogger, process_page, get_page_by_tag_slug, get_pages_by_tag
from app.pages.views import render


@mod.route('/<string:tag>/<string:slug>', methods=['GET'])
def show_page_tag(tag, slug):
    page = get_page_by_tag_slug(tag, slug)
    if page is None:
        abort(404)

    canedit = isblogger(current_user=g.user)
    process_page(page, render=render)

    return render_template(
        "pages/page.html"
        , page=page
        , isblogger=canedit
    )


from app import app
from app.admin.storage import ul_menu_creation


@app.context_processor
def custom_function():
    def ul_menu(tag):
        return ul_menu_creation(tag)

    def li_menu(tag):
        return ul_menu_creation(tag, use_ul=False)

    return dict(ul_menu=ul_menu, li_menu=li_menu)

app/users/views.py
import os
import md5
import hashlib
import base64
from flask import Blueprint, request, render_template
from flask import flash, g, session, redirect, url_for
from flask import make_response
from flask import current_app
from flask_mail import Message
from werkzeug import secure_filename
from app import db
from app import mail
from app.mail_utility import send_email
from app.users.forms import RegisterForm, LoginForm, ProfileForm, ForgotForm
from app.users.constants import UPLOAD_FOLDER
from app.users.models import User, Role, users_roles
from app.users.utils import allowed_image_file
from app.users.decorators import login_required, templated
from itsdangerous import URLSafeTimedSerializer
from flask.ext.babel import gettext
from flask.ext.security.utils import encrypt_password, verify_password
from flask.ext.principal import identity_changed, Identity, AnonymousIdentity

from app import guest_per, user_per, blogger_per, admin_per

mod = Blueprint('users', __name__, url_prefix='/users')


def authorize(user):
    session['user_id'] = user.id


def is_logged():
    return g.user


@mod.before_app_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])


@mod.route('/dashboard')
@mod.route('/home')
@user_per.require(http_exception=403)
def home():
    return render_template(
        "users/me.html", user=g.user
    )


@mod.route('/pleaseconfirm')
def pleaseconfirm():
    if g.user:
        send_confirmation()
    return render_template("users/pleaseconfirm.html", user=g.user)


@mod.route("/confirm/<string:token>", methods=['GET', 'POST'])
def confirm(token):
    """docstring for confirm"""
    try:
        email = confirm_token(token)
    except:
        flash(gettext(u'The confirmation link is invalid or has expired.'), 'danger')

    user = User.query.filter_by(email=email).first_or_404()

    if user.is_confirmed():
        flash(gettext(u'Account already confirmed. Please login.'), 'success')
    else:
        user.confirmed = True
        user.active = True
        db.session.commit()
        flash(gettext(u'You have confirmed your account. Thanks!'), 'success')

    return redirect(url_for('users.home'))


def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    return serializer.dumps(email, salt=current_app.config['SECURITY_PASSWORD_SALT'])


def confirm_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    try:
        email = serializer.loads(
            token,
            salt=current_app.config['SECURITY_PASSWORD_SALT'],
            max_age=expiration
        )
    except:
        return False
    return email


@mod.route("/reconfirm/<string:alias>", methods=['GET', 'POST'])
def reconfirm(alias):
    """docstring for reconfirm"""
    if g.user:
        send_confirmation()
    return redirect(url_for('users.home'))


def send_confirmation():
    """docstring for send_confirmation"""

    token = generate_confirmation_token(str(g.user.get_email()))
    lnk = url_for('users.confirm', token=token, _external=True)
    conflnk_html = '<a href="%s">%s</a>' % (lnk, lnk)

    msg = Message(
        gettext(u"Please confirm your account at vision website"),
        sender=current_app.config['NOREPLY_EMAIL'],
        recipients=[g.user.get_email()]
    )
    msg.body = "\nWelcome\n\n"
    msg.body += "\nPlease confirm your account by clicking this link:\n"
    msg.body += "\n%s" % lnk
    msg.body += "\nFuture notifications will be sent to this email address."
    msg.body += "\nThank you,"
    msg.body += "\n\nTeam."

    msg.html = "Hi, Welcome"
    msg.html += "<br><br>Please confirm your account by clicking this link:"
    msg.html += "\n%s" % conflnk_html
    msg.html += "<br>Future notifications will be sent to this email address."
    msg.html += "<br>Thank you,"
    msg.html += "<br><br>Team."
 
 
    if current_app.config['SEND_EMAILS'] == True:
        mail.send(msg)


# @mod.route('/forgot-password', methods=['GET', 'POST'])
# def forgot():
#     if 'user_id' in session:
#         return redirect(url_for('users.home'))
#
#     form = ForgotForm(request.form)
#     if request.method == 'POST':
#         if form.validate_on_submit():
#             user = User.query.filter_by(email=form.email.data).first()
#             if user:
#                 return user
#
#     # make sure data are valid, but doesn't validate password is right
#     return render_template("users/forgot.html", form=form)



@mod.route('/login', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    if 'user_id' in session:
        return redirect(url_for('users.home'))

    form = LoginForm(request.form)

    # make sure data are valid, but doesn't validate password is right
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            # we use werzeug to validate user's password
            if user and verify_password(form.password.data, user.password):
                # the session can't be modified as it's signed,
                # it's a safe place to store the user id
                authorize(user)
                # Tell Flask-Principal the identity changed
                identity_changed.send(current_app._get_current_object(),
                                      identity=Identity(user.id))

                flash(gettext(u'Welcome') + " " + user.name)
                if not user.is_confirmed():
                    return redirect(url_for('users.pleaseconfirm', next=url_for('home.home')))
                return redirect(url_for('home.home'))
        flash(gettext(u'Wrong email or password'), 'error-message')

    return render_template('users/login.html', form=form)


@mod.route('/logout', methods=['GET'])
def logout():
    """ Logout action.  """
    if 'user_id' in session:
        del session['user_id']
        g.user = None

        # Tell Flask-Principal the user is anonymous
    identity_changed.send(current_app._get_current_object(),
                          identity=AnonymousIdentity())

    response = make_response(redirect(url_for('users.login')))
    response.set_cookie('sc', '', expires=0)
    return response


@mod.route('/register', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # create an user instance not yet stored in the database
        # check if email exists
        try:
            exists = db.session.query(User).filter(
                User.email == form.email.data).first()

            if exists:
                flash(
                    gettext(
                        u'User with this e-mail was registered already.'
                        u' If you forgot your password click ' +
                        u'<a href="%s">remind password</a>' % url_for(
                            'users.forgot')
                    ))
                # redirect user to the 'home' method of the user module.
                return redirect(url_for('users.register'))
        except Exception as e:
            current_app.logger.exception(e)

        alias = ''.join(e for e in form.name.data if e.isalnum())
        try:
            alias_exists = db.session.query(User).filter(
                User.alias == alias).one()
        except Exception as e:
            current_app.logger.exception(e)
            alias_exists = None

        if alias_exists:
            alias = hashlib.md5(form.email.data).hexdigest()

        user = User(
            name=form.name.data,
            email=form.email.data,
            alias=alias,
            password=encrypt_password(form.password.data)
        )

        # add default
        userRole = db.session.query(Role).filter(Role.name == "user").first()
        if userRole is not None:
            # createUserRole =  users_roles( user_id = user.id
            #     , role_id = userRole.id );
            # adminRole =  db.session.query(Role).filter(Role.name == "admin").first()
            # user.roles.append(adminRole)
            user.roles.append(userRole)

        # Insert the record in our database and commit it
        db.session.add(user)
        db.session.flush()

        # Log the user in, as he now has an id
        authorize(user)

        try:
            os.mkdir(os.path.join(UPLOAD_FOLDER, str(user.id)), 0775)
        except OSError as e:
            current_app.logger.exception(e)

        db.session.commit()
        email_recipients = [item.email for item in db.session.query(User).all()
                            if item.has_role(Role.query.get(1))
                            ]
        msg = 'A new user with login {} was created'.format(user.name)

        if current_app.config['SEND_EMAILS'] == True:
            try:
                send_email(email_recipients, msg)
            except Exception as e:
                pass

        # flash will display a message to the user
        flash(gettext(u'Thanks for registering'))
        # redirect user to the 'home' method of the user module.
        if not user.is_confirmed():
            return redirect(url_for('users.pleaseconfirm', next=url_for('users.home')))

    return render_template('users/register.html', form=form)


@mod.route("/profile", methods=['GET', 'POST'])
@user_per.require(http_exception=403)
@templated('users/profile.html')
def profile():
    user = g.user
    form = ProfileForm(request.form, obj=user)

    if form.validate_on_submit():
        user.name = form.name.data
        user.mobile = form.mobile.data
        user.website = form.website.data
        user.description = form.description.data

        if 'photo' in request.files:
            # remove user photo and thumbs

app/templates/widgets/analytics.html
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-68529106-1', 'auto');
ga('send', 'pageview');

</script>

app/templates/widgets/bottom-menu.html
<div class="center-divider"></div>

app/templates/widgets/dashboard-flash.html
{% with messages = get_flashed_messages() %}
		{% for category, msg in get_flashed_messages(with_categories=true) %}
			<div class="alert alert-{{ category }} alert-dismissable">{{ msg }}</div>
		{% endfor %}
{% endwith %}

app/templates/widgets/dashboard-menu.html
<div class="modal hide" id="pleaseWaitDialog" data-backdrop="static" data-keyboard="false">
  <div class="modal-header">
  </div>
  <div class="modal-body">
    <div class="progress progress-striped active">
      <div class="bar" style="width: 100%;"></div>
    </div>
  </div>
</div>
<nav class="navbar navbar-default" role="navigation">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a href="{{ url_for('users.home') }}"><span class="glyphicon glyphicon-home home"></span></a>
</div>
</nav>

app/templates/widgets/dashboard-top-menu.html
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav w1000">
        <li class="active"><a href="{{ url_for('users.home') }}">Dashboard</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li class="pull-left active">
          </li>
        <li class="dropdown ">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.name }} {% if user.avatar is defined %}<img src="{{user.avatar(28)}}">{% endif %}<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="{{ url_for('users.home') }}"><span class="glyphicon glyphicon-dashboard"></span>&nbsp;Dashboard</a></li>
                <li><a href="{{ url_for('users.profile') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Edit Profile</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('users.logout') }}"><span class="glyphicon glyphicon-off"></span>&nbsp;Logout</a></li>
            </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/templates/widgets/flash.html
<div id="messages-wrap">
	<div id="messages">
		{% for category, msg in get_flashed_messages(with_categories=true) %}
		<p class="message flash-{{ category }}">{{ msg }}</p>
		{% endfor %}
	</div>
</div>

app/templates/widgets/footer.html
<footer>
<div class="arial container">
  <a href="/">
    <div class="logo"></div>
  </a>
  <div class="left-footer">
    <div>© 2015-2018 Vision Diagnostic</div>
  </div>
  <div class="right-footer">
	  <div style="float:right">
	  </div>
	  <ul class="footer-menu">
		  <li class="active"><a href="/">{{ _('Home') }}</a></li>
		  <li><a href="{{ url_for('users.register') }}">{{ _('Register') }}</a></li>
		  <li><a href="{{ url_for('users.login') }}">{{ _('Login') }}</a></li>
	  </ul>
	  <div>
	  </div>
  </div>
</div>
</footer>

app/templates/widgets/topmenu.html
{% block navbar %}
<div class="navbar navbar-default " role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{{ url_for('home.home') }}">{{ _('Vision Diagnostic') }}</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li {% if request.path == "/content/page/1/" %} class="active" {% endif %}>
				<a href="{{ url_for('blogging.page_by_id', post_id=1) }}">{{ _('About') }}</a></li>
				<li><a href="/forum"><i class="fa fa-comment"></i>&nbsp;{{ _('Forum') }}</a></li>
				<li>
					<ul class="nav navbar-nav">
						<li> 
							<a href="#" class="dropdown-toggle active" data-toggle="dropdown">Wiki <span class="caret"></span></a>
							
							<ul class='dropdown-menu multi-level'>
								<li><a href="/wiki/vision-diagnostic-objectives">Objectives</a></li>
								<li><a href="/wiki/Users">Users</a></li>
								<li><a href="/wiki/How to">How to</a></li>
								<li><a href="/manual/technical-information">Technical Information</a></li>
								<li><a href="/wiki/developers">Developers</a></li>
							</ul>
						</li>
					</ul>
				</li>
                <li><a href="http://159.203.47.5/" title="WITTAM is a transformer thermal model simulator in steady and transient mode. Include moisture and gas (future) modeling partition between oil and paper">
                    <i class="fa fa-connectdevelop"></i>&nbsp;{{ _('Transformer thermal model simulator') }}</a></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				{% block navbar_right %}
				{% if current_user.is_authenticated() %}
				<li><a href="{{ url_for('admin.index') }}" title="{{ current_user.name|striptags|title }}'s dashboard">{{ _('Dashboard') }}</a></li>
				<li><a href="{{ url_for('users.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;{{ _('Logout') }}</a></li>
				{% else %}
				<li><a href="{{ url_for('users.register') }}">{{ _('Register') }}</a></li>
				<li><a href="{{ url_for('users.login') }}">{{ _('Login') }}</a></li>
				{% endif %}

				<li class="dropdown">
					<a href="#" class="dropdown-toggle"
						data-toggle="dropdown" role="button"
						aria-haspopup="true" aria-expanded="false">{{ g.locale|upper }}&nbsp;<span class="caret"></span></a>
					<ul class="dropdown-menu">
						{% for lang in config.LANGUAGES %}
							<li><a href="{{ url_for('home.lang', lang=lang) }}">{{ lang|upper }}</a></li>
						{% endfor %}
					</ul>
				</li>
				{% endblock %}
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.container-fluid -->
</div>
{% endblock %}