app/tree/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, request, render_template
from flask import flash, g, session
from app.users.models import User
from .storage import *
from flask import jsonify
from .forms import TreeView
from app import admin_per
from flask import redirect, url_for
import app.diagnostic.models as DiagnosticModel
from app.diagnostic.models import *

mod = Blueprint('tree', __name__, url_prefix='/admin/tree')


@mod.before_app_request
def before_request():
    set_locale()
    g.user = None
    if 'user_id' in session:
        if session['user_id'] is not None:
            g.user = User.query.get(session['user_id'])


@mod.route("/rename/", methods=['POST'])
def rename():
    if request.is_xhr:
        success = False
        if admin_per.require().can():
            if request.form['id']:
                success = rename_node(id=request.form['id'], text=request.form['text'])

        return jsonify({'success': success})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/create/", methods=['POST'])
def create():
    if request.is_xhr:
        id = None
        if admin_per.require().can():
            if request.form['parent']:
                id = create_node(parent=request.form['parent'], text=request.form['text']
                                 , icon=request.form['icon'], type=request.form['type'],
                                 tooltip=request.form['tooltip'])

        return jsonify({'id': id})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/delete/", methods=['POST'])
def delete():
    if request.is_xhr:
        id = None
        if admin_per.require().can():
            if request.form['id']:
                id = delete_node(id=request.form['id'])

        return jsonify({'id': id})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/update/", methods=['POST'])
def update():
    if request.is_xhr:
        status = "NOK"
        ret_id = None
        tooltip = None
        if admin_per.require().can():
            form = TreeView(request.form)
            if form.validate():
                res = update_node(request.form['node_id'], request.form['view'], request.form['tooltip'])
                if res is not None:
                    ret_id = request.form['node_id']
                    tooltip = request.form['tooltip']
                    status = "OK"
        return jsonify({'status': status, 'id': ret_id, 'tooltip': tooltip})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/getview/", methods=['POST'])
def getview():
    if request.is_xhr:
        retView = None
        tooltip = None
        if admin_per.require().can():
            if request.form['node_id']:
                res = get_view_by_id(request.form['node_id'])
                if res is not None:
                    retView, tooltip = res

        return jsonify({'view': retView, 'tooltip': tooltip})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/renderview/", methods=['POST'])
def renderview():
    if request.is_xhr:
        template = None
        if request.form['node_id']:
            view = get_view_by_id(request.form['node_id'])
            data = "views/" + view + ".html"
            template = render_template(data)

        return template
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/move/", methods=['POST'])
def move():
    if request.is_xhr:
        status = "NOK"
        if request.form['node_id']:
            res = move_node(request.form['node_id'], request.form['parent_id'])
            if res is not None:
                status = "OK"
        return jsonify({'status': status})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/move_to_location/", methods=['POST'])
def move_to_location():
    if request.is_xhr:
        status = "NOK"
        if request.form['node_id']:
            res = move_node_to_location(request.form['node_id'], request.form['location_id'])
            if res is not None:
                status = "OK"
        return jsonify({'status': status})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/copy/", methods=['POST'])
def copy():
    if request.is_xhr:
        status = "NOK"
        if request.form['node_id']:
            res = copy_node(request.form['node_id'], request.form['parent_id'])
            if res is not None:
                status = "OK"

        return jsonify({'status': status})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/join/", methods=['POST'])
def join():
    if request.is_xhr:
        status = "NOK"
        if request.form['node_id']:
            res = join_node(request.form['node_id'], request.form['to_join'])
            if res is not None:
                status = "OK"

        return jsonify({'status': status, 'joined': res})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route("/status/", methods=['POST'])
def status():
    if request.is_xhr:
        status = "NOK"
        src = ''
        if request.form['node_id']:
            res = change_status(request.form['node_id'], request.form['status'])
            if res is not None:
                status = "OK"
                src = res

        return jsonify({'status': status, 'src': src})
    else:
        # redirect to home
        return redirect(url_for('home.home'))


@mod.route('/graph/', methods=['GET'])
def graph():
    ids = request.args.get('id')
    id = ids.split(',')
    ids = []
    for value in id:
        if value != "null" and value:
            ids.append(value)
    json_res = GraphData(equipment_id=ids).fetch()
    
    return json.dumps(json_res)

@mod.route('/graph/search/', methods=['GET'])
def graph_search():
    ids = request.args.get('equipmentId')
    date = request.args.get('date')
    id = ids.split(',')
    ids = []
    for value in id:
        if value != "null" and value:
            ids.append(value)
    equipments = db.session.query(Equipment).filter(Equipment.id.in_(ids)).values('name')
    equipments = [equipment.name for equipment in equipments]
    json_res = GraphData(equipment_id=ids).search({'date':date})
    
    return json.dumps({"equipment" : equipment, "data": json_res})

@mod.route('/item_details/<id>/', methods=['GET'])
def item_details(id):
    
    equipment = db.session.query(Equipment).filter(Equipment.id == id).first().serialize()
    mod = DiagnosticModel.get_class_by_tablename(equipment['equipment_type']['table_name'])
    res = db.session.query(mod).filter(mod.equipment_id == id).first().serialize()

    equipment['norm_type'] = "standart"
    norms = db.session.query(Norm).all()
    for norm in norms:
        norm = norm.serialize()
        data_mod = DiagnosticModel.get_class_by_tablename(norm['table_name'] + "_data")
        data = db.session.query(data_mod).filter(data_mod.equipment_id == id).count()
        if data > 0:
            equipment['norm_type'] = "custom"
            equipment['norm_option_text'] = {"name" : norm['table_name'], "id" : norm['id'], "text" : norm['name']}
            break
        
    return json.dumps({'equipment':equipment, 'equipment_item':res})

app/templates/admin.html
{% extends 'admin/base.html' %}

{% block head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/css/jquery.fancybox.min.css" type="text/css" media="screen" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='build/admin.min.css') }}">
    <script type="text/javascript">
        var url = {
            update: '{{ url_for("tree.update") }}',
            create: '{{ url_for("tree.create") }}',
            delete: '{{ url_for("tree.delete") }}',
            rename: '{{ url_for("tree.rename") }}',
            move: '{{ url_for("tree.move") }}',
            copy: '{{ url_for("tree.copy") }}',
            getView: '{{ url_for("tree.getview") }}',
            treeUpdate: '{{ url_for("tree.update") }}',
            treeStatus: '{{ url_for("tree.status") }}',
            treeJoin: '{{ url_for("tree.join") }}',
            treeCreate: '{{ url_for("tree.create") }}',
            treeDelete: '{{ url_for("tree.delete") }}',
            treeRename: '{{ url_for("tree.rename") }}',
            treeMove: '{{ url_for("tree.move") }}',
            treeMoveToLocation: '{{ url_for("tree.move_to_location") }}',
            treeCopy: '{{ url_for("tree.copy") }}',
            treeGetView: '{{ url_for("tree.getview")}}',
            graph: '{{ url_for("tree.graph")}}',
            graph_details: '{{ url_for("tree.graph_search")}}',
            info: '{{ url_for("tree.item_details", id=":id")}}'
        };
        var equipTypeToUrl = {{ _(equipTypeToUrl) }};
        var treeStruct = {{ _(tree) or '[]' }};
        var switchIds = {{ _(switchIds) or '[]' }};
{#</div>#}
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-shim.min.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-sham.min.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.2/es6-sham.min.js"></script> 
    <script src="https://wzrd.in/standalone/es7-shim@latest"></script>
{% endblock head %}

{% block main_menu %}
	<div id="navbar" class="navbar-collapse collapse in">
        {{ super() }}
        {% if current_user.is_authenticated() %}
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-large" ></i>
                        {{ current_user.login }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="{{ url_for('admin.logout_view') }}">Log out</a>
                        </li>
                    </ul>
                </li>
            </ul>
        {% endif %}
    </div>
{% endblock main_menu %}

{% block tail %}
    <script src="{{ url_for('static', filename='js/jstree.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/selectize.min.js') }}"></script>
{#    <script src="{{ url_for('static', filename='src/diagnostic/Tree.js') }}"></script>#}
    <script>
        var WebFontConfig = {
          google: { families: [ 'Roboto:400,300,500:latin' ] }
        };
        (function() {
          var wf = document.createElement('script');
          wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
          wf.type = 'text/javascript';
          wf.async = 'true';
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(wf, s);
        })();
    </script>
  {% if user_is_admin %}
    <script src="{{ url_for('static', filename='build/app.js') }}"></script>
  {% else %}
    <script src="{{ url_for('static', filename='build/performer.js') }}"></script>
  {% endif %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js"></script>
{% endblock tail %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
        <title>{% block title %}Vision Diagnostic{% endblock %}</title>
        <meta name=viewport content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="">
        <meta charset="utf-8">
        <!-- SUPPORT FOR IE6-8 OF HTML5 ELEMENTS -->
        <!--[if lt IE 9]>
              <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
          <![endif]-->

        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
        {% block style %}
        {% endblock style %}
        {% block extrastyle %}
        {% endblock extrastyle %}
    {% endblock %}
    {% include 'widgets/analytics.html' %}
  </head>
  <body>
	{% include 'widgets/topmenu.html' %}
    {% block header %}
    {% endblock %}
    {% block top %}
    <div class="{% block top_banner %}home-main{% endblock %}">
      <div class="w1000">
        <div>
          <a href="{{ url_for('home.home') }}">
            <div class="logo"></div>
          </a>
          <div class="right-section">
          </div>
          <div class="clear"></div>
        </div>
      </div>
    </div>
    {% endblock %}
    {% include 'widgets/flash.html' %}
    {% block content %}
    <div class="center-divider"></div>
    <div class="h800 container page">
      <div class="">
        {% block leftcontent %}
        {% endblock leftcontent %}
        {% block topcontent %}
        {% endblock %}
        {% block rightcontent %}
        <div class="right-side"></div>
        {% endblock %}
        <div class="clear"></div>
      </div>
    </div>
    {% endblock %}
    {% block bottommenu %}
    {% include 'widgets/bottom-menu.html' %}
    {% endblock %}
    {% block footer %}
    <div class="center-divider"></div>
    {% include 'widgets/footer.html' %}
    {% endblock %}
    {% block js_footer %}
        {% block extrajs %}
            <script src="{{ url_for('static', filename='js/jquery-1.9.1.min.js') }}"></script>
            <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
            <script src="{{ url_for('static', filename='bootstrap/js/jquery-ui.min.js') }}"></script>
            <script src="{{ url_for('static', filename='js/common.js') }}"></script>

			<script type="text/javascript" >
				<!--$(document).ready(function(){-->
					<!--$(".dropdown-menu > li > a.trigger").on("click",function(e){-->
						<!--console.log();-->
						<!--var current = $(this).next();-->
						<!--var grandparent=$(this).parent().parent();-->
						<!--if($(this).hasClass('left-caret')||$(this).hasClass('right-caret'))-->
							<!--$(this).toggleClass('right-caret left-caret');-->
						<!--grandparent.find('.left-caret').not(this).toggleClass('right-caret left-caret');-->
						<!--grandparent.find(".sub-menu:visible").not(current).hide();-->
						<!--current.toggle();-->
						<!--e.stopPropagation();-->
					<!--});-->

					<!--$(".dropdown-menu > li > a:not(.trigger)").on("click",function(){-->
						<!--var root=$(this).closest('.dropdown');-->
						<!--root.find('.left-caret').toggleClass('right-caret left-caret');-->
						<!--root.find('.sub-menu:visible').hide();-->
					<!--});-->
				<!--});-->
			</script>

            {% block js %}
            {% endblock %}
        {% endblock extrajs %}
    {% endblock %}
  </body>
</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% block head %}
		<title>{{ user.name }}'s dashboard '{% block title %}{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta name="author" content="">
		<meta charset="utf-8">
		<!-- SUPPORT FOR IE6-8 OF HTML5 ELEMENTS -->
		<!--[if lt IE 9]>
					<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
			<![endif]-->
		<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/dashboard.css') }}">
		<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
		{% endblock %}
<body>
{% include 'widgets/dashboard-top-menu.html' %}
<div class="center-divider"></div>
<div class="grey-background profile-page">
{% block page %}
	<div class="container">
         <div class="panel-default panel page rmBottom">
            {% include 'widgets/dashboard-flash.html' %}
            <div class="panel-heading">{% block dashboard_menu %}{% endblock %}</div>
            <div class="panel-body">
                {% block panel_body %}
                {% endblock %}
            </div>
            {% block content %}
            {% endblock %}
        </div>
    </div>
	{% block content_footer %}
	<div class="container">
        <div class=" panel-footer">
            {% block panel_footer %}
            {% endblock %}
	    </div>
    </div>
	{% endblock %}
{% endblock %}
</div>
<p>&nbsp;</p>

{% block bottommenu %}
{% include 'widgets/bottom-menu.html' %}
{% endblock %}

{% block footer %}
{% include 'widgets/footer.html' %}
{% endblock %}
	<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject_src.js"></script>

	<script src="{{ url_for("static", filename="js/upload/vendor/jquery.ui.widget.js") }}"></script>
	<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
	<!-- The basic File Upload plugin -->
	<script src="{{ url_for("static", filename="js/upload/jquery.fileupload.js") }}"></script>
	<script src="{{ url_for("static", filename="js/upload/jquery.iframe-transport.js") }}"></script>
	{#
	<!-- The File Upload processing plugin -->
	<script src="{{ url_for("static", filename="js/upload/jquery.fileupload-process.js") }}"></script>
	<!-- The File Upload validation plugin -->
	<script src="{{ url_for("static", filename="js/upload/jquery.fileupload-validate.js") }}"></script>
	#}
</body>
</html>

app/templates/pdf.html
<!doctype html>
<html>
    <head>
        <title>Equipment Report</title>
        <script src="https://d3js.org/d3.v4.min.js"></script>

    </head>
    <body>
        <h2 id="test">Equipment Reporttt</h2>

        <table width="100%" border="1">
            <thead>
                <tr>
                    <th colspan="6">Equipment Information</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Id:</td>
                    <td>999</td>
                    <td>Serial No:</td>
                    <td>05627-2	Name:</td>
                    <td>REG 51</td>
                </tr>
            </tbody>
        </table>
        <svg width="960" height="500" >
            <circle r="100" stroke="brown" stroke-opacity="0.5" fill="none"></circle>
            <circle r="200" stroke="steelblue" stroke-opacity="0.5" fill="none"></circle>
        </svg>
        <script>
                document.getElementById("test").innerText = "aaaaa";
            </script>
    </body>
</html>